=== trympet/blue-sector-mirror/Assets/FishFeeding/LevelSystem/LevelList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="modes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mode" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tutorial" type="xs:boolean" />
                            <xs:element name="time" type="xs:integer" />
                            <xs:element name="threshold" type="xs:float" />
                            <xs:element name="unlock" type="xs:integer" />
                            <xs:element name="modifier" type="xs:float" />
                            <xs:element name="unlocked" type="xs:boolean" />
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== trympet/blue-sector-mirror/Assets/FishFeeding/LevelSystem/LevelList.xml
<?xml version="1.0" encoding="UTF-8"?>
<modes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="LevelList.xsd">
    <!-- Arcade mode levels (easier difficulty, lower thresholds, more gameified) -->
        <mode name="arcade">                         <!-- Mode --> 
            <tutorial>true</tutorial>   <!-- Does this mode have a tutorial -->
            <time>120</time>
            <threshold>0.1</threshold>  <!-- How low is feed% before failing -->
            <unlock>0</unlock>          <!-- Score to unlock mode -->
            <modifier>0.0</modifier>    <!-- Modifier for difficulty level -->
            <unlocked>true</unlocked>       <!-- Is mode unlocked? -->
        </mode>

    <!-- Realism mode levels (harder difficulty, higher thresholds, more detail) -->
    <mode name="realism">
        <tutorial>true</tutorial>
        <time>480</time>
        <threshold>0.1</threshold>
        <unlock>0</unlock>
        <modifier>0.0</modifier>
        <unlocked>false</unlocked>
    </mode>

    <!-- Sandbox mode -->
    <mode name="sandbox">
        <tutorial>false</tutorial>
        <time>0</time>
        <threshold>0.1</threshold>
        <unlock>0</unlock>
        <modifier>0.0</modifier>
        <unlocked>true</unlocked>
    </mode>
</modes>
